### ISSUE TITLE
Can't resolve electron-splashscreen/office.html

### ISSUE THREAD

**Issue by pablocar80** [bkniffler/electron-splashscreen#2]
Hello!

When running the example, this line:

`require.resolve('electron-splashscreen/office.html')`

Gives me the following error:

`Module not found: Error: Can't resolve 'electron-splashscreen/office.html'`

I checked your source files and there is no office.html, and instead an office.ts. Is there a step I am missing?

Thank you!!

**Comment by bkniffler** [comment]
Ah, sorry, just saw the issues here, didn't have automatic notifications enabled

If this is still an issue:
```
import initSplash, { Office } from 'electron-splashscreen';
initSplash({
      url: Office,
      ... other options
    });
```
I'll update the docs!
